// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stat.proto

package com.zhouyp.demo.proto.RtaStat;

public final class Stat {
  private Stat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zhouyp.demo.proto.RtaStat.DB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */
    int getTablesCount();
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */
    boolean containsTables(
        java.lang.String key);
    /**
     * Use {@link #getTablesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
    getTables();
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */
    java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
    getTablesMap();
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */

    com.zhouyp.demo.proto.RtaStat.Stat.Table getTablesOrDefault(
        java.lang.String key,
        com.zhouyp.demo.proto.RtaStat.Stat.Table defaultValue);
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */

    com.zhouyp.demo.proto.RtaStat.Stat.Table getTablesOrThrow(
        java.lang.String key);

    /**
     * <pre>
     *起始时间戳，Unix Timestamp的整型秒，两次发起的请求时间戳范围可能会有重叠，请使用新的覆盖老的
     * </pre>
     *
     * <code>int64 Timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *每个Value的间隔，单位秒。例如分钟级的统计，该值为60。对于每个Value，其隐含代表的时间戳为 Timestamp + (n * Interval)。n=0 to len()-1；
     * </pre>
     *
     * <code>int64 Interval = 3;</code>
     */
    long getInterval();
  }
  /**
   * Protobuf type {@code com.zhouyp.demo.proto.RtaStat.DB}
   */
  public  static final class DB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zhouyp.demo.proto.RtaStat.DB)
      DBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DB.newBuilder() to construct.
    private DB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DB() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tables_ = com.google.protobuf.MapField.newMapField(
                    TablesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
              tables__ = input.readMessage(
                  TablesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              tables_.getMutableMap().put(
                  tables__.getKey(), tables__.getValue());
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 24: {

              interval_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_DB_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTables();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_DB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhouyp.demo.proto.RtaStat.Stat.DB.class, com.zhouyp.demo.proto.RtaStat.Stat.DB.Builder.class);
    }

    private int bitField0_;
    public static final int TABLES_FIELD_NUMBER = 1;
    private static final class TablesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>newDefaultInstance(
                  com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_DB_TablesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.zhouyp.demo.proto.RtaStat.Stat.Table.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> tables_;
    private com.google.protobuf.MapField<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
    internalGetTables() {
      if (tables_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TablesDefaultEntryHolder.defaultEntry);
      }
      return tables_;
    }

    public int getTablesCount() {
      return internalGetTables().getMap().size();
    }
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */

    public boolean containsTables(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTables().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTablesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> getTables() {
      return getTablesMap();
    }
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */

    public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> getTablesMap() {
      return internalGetTables().getMap();
    }
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */

    public com.zhouyp.demo.proto.RtaStat.Stat.Table getTablesOrDefault(
        java.lang.String key,
        com.zhouyp.demo.proto.RtaStat.Stat.Table defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> map =
          internalGetTables().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *表格，Key为Table名，Value为具体的Table内容
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
     */

    public com.zhouyp.demo.proto.RtaStat.Stat.Table getTablesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> map =
          internalGetTables().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <pre>
     *起始时间戳，Unix Timestamp的整型秒，两次发起的请求时间戳范围可能会有重叠，请使用新的覆盖老的
     * </pre>
     *
     * <code>int64 Timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int INTERVAL_FIELD_NUMBER = 3;
    private long interval_;
    /**
     * <pre>
     *每个Value的间隔，单位秒。例如分钟级的统计，该值为60。对于每个Value，其隐含代表的时间戳为 Timestamp + (n * Interval)。n=0 to len()-1；
     * </pre>
     *
     * <code>int64 Interval = 3;</code>
     */
    public long getInterval() {
      return interval_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTables(),
          TablesDefaultEntryHolder.defaultEntry,
          1);
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (interval_ != 0L) {
        output.writeInt64(3, interval_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> entry
           : internalGetTables().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
        tables__ = TablesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, tables__);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (interval_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, interval_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhouyp.demo.proto.RtaStat.Stat.DB)) {
        return super.equals(obj);
      }
      com.zhouyp.demo.proto.RtaStat.Stat.DB other = (com.zhouyp.demo.proto.RtaStat.Stat.DB) obj;

      if (!internalGetTables().equals(
          other.internalGetTables())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getInterval()
          != other.getInterval()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetTables().getMap().isEmpty()) {
        hash = (37 * hash) + TABLES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTables().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInterval());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.DB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhouyp.demo.proto.RtaStat.Stat.DB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhouyp.demo.proto.RtaStat.DB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zhouyp.demo.proto.RtaStat.DB)
        com.zhouyp.demo.proto.RtaStat.Stat.DBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_DB_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetTables();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableTables();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_DB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhouyp.demo.proto.RtaStat.Stat.DB.class, com.zhouyp.demo.proto.RtaStat.Stat.DB.Builder.class);
      }

      // Construct using com.zhouyp.demo.proto.RtaStat.Stat.DB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableTables().clear();
        timestamp_ = 0L;

        interval_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_DB_descriptor;
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.DB getDefaultInstanceForType() {
        return com.zhouyp.demo.proto.RtaStat.Stat.DB.getDefaultInstance();
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.DB build() {
        com.zhouyp.demo.proto.RtaStat.Stat.DB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.DB buildPartial() {
        com.zhouyp.demo.proto.RtaStat.Stat.DB result = new com.zhouyp.demo.proto.RtaStat.Stat.DB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.tables_ = internalGetTables();
        result.tables_.makeImmutable();
        result.timestamp_ = timestamp_;
        result.interval_ = interval_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhouyp.demo.proto.RtaStat.Stat.DB) {
          return mergeFrom((com.zhouyp.demo.proto.RtaStat.Stat.DB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhouyp.demo.proto.RtaStat.Stat.DB other) {
        if (other == com.zhouyp.demo.proto.RtaStat.Stat.DB.getDefaultInstance()) return this;
        internalGetMutableTables().mergeFrom(
            other.internalGetTables());
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getInterval() != 0L) {
          setInterval(other.getInterval());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhouyp.demo.proto.RtaStat.Stat.DB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhouyp.demo.proto.RtaStat.Stat.DB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> tables_;
      private com.google.protobuf.MapField<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
      internalGetTables() {
        if (tables_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TablesDefaultEntryHolder.defaultEntry);
        }
        return tables_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
      internalGetMutableTables() {
        onChanged();;
        if (tables_ == null) {
          tables_ = com.google.protobuf.MapField.newMapField(
              TablesDefaultEntryHolder.defaultEntry);
        }
        if (!tables_.isMutable()) {
          tables_ = tables_.copy();
        }
        return tables_;
      }

      public int getTablesCount() {
        return internalGetTables().getMap().size();
      }
      /**
       * <pre>
       *表格，Key为Table名，Value为具体的Table内容
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
       */

      public boolean containsTables(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTables().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTablesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> getTables() {
        return getTablesMap();
      }
      /**
       * <pre>
       *表格，Key为Table名，Value为具体的Table内容
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
       */

      public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> getTablesMap() {
        return internalGetTables().getMap();
      }
      /**
       * <pre>
       *表格，Key为Table名，Value为具体的Table内容
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
       */

      public com.zhouyp.demo.proto.RtaStat.Stat.Table getTablesOrDefault(
          java.lang.String key,
          com.zhouyp.demo.proto.RtaStat.Stat.Table defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> map =
            internalGetTables().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *表格，Key为Table名，Value为具体的Table内容
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
       */

      public com.zhouyp.demo.proto.RtaStat.Stat.Table getTablesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> map =
            internalGetTables().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTables() {
        internalGetMutableTables().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *表格，Key为Table名，Value为具体的Table内容
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
       */

      public Builder removeTables(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTables().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table>
      getMutableTables() {
        return internalGetMutableTables().getMutableMap();
      }
      /**
       * <pre>
       *表格，Key为Table名，Value为具体的Table内容
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
       */
      public Builder putTables(
          java.lang.String key,
          com.zhouyp.demo.proto.RtaStat.Stat.Table value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTables().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *表格，Key为Table名，Value为具体的Table内容
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Table&gt; Tables = 1;</code>
       */

      public Builder putAllTables(
          java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Table> values) {
        internalGetMutableTables().getMutableMap()
            .putAll(values);
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *起始时间戳，Unix Timestamp的整型秒，两次发起的请求时间戳范围可能会有重叠，请使用新的覆盖老的
       * </pre>
       *
       * <code>int64 Timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *起始时间戳，Unix Timestamp的整型秒，两次发起的请求时间戳范围可能会有重叠，请使用新的覆盖老的
       * </pre>
       *
       * <code>int64 Timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *起始时间戳，Unix Timestamp的整型秒，两次发起的请求时间戳范围可能会有重叠，请使用新的覆盖老的
       * </pre>
       *
       * <code>int64 Timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long interval_ ;
      /**
       * <pre>
       *每个Value的间隔，单位秒。例如分钟级的统计，该值为60。对于每个Value，其隐含代表的时间戳为 Timestamp + (n * Interval)。n=0 to len()-1；
       * </pre>
       *
       * <code>int64 Interval = 3;</code>
       */
      public long getInterval() {
        return interval_;
      }
      /**
       * <pre>
       *每个Value的间隔，单位秒。例如分钟级的统计，该值为60。对于每个Value，其隐含代表的时间戳为 Timestamp + (n * Interval)。n=0 to len()-1；
       * </pre>
       *
       * <code>int64 Interval = 3;</code>
       */
      public Builder setInterval(long value) {
        
        interval_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *每个Value的间隔，单位秒。例如分钟级的统计，该值为60。对于每个Value，其隐含代表的时间戳为 Timestamp + (n * Interval)。n=0 to len()-1；
       * </pre>
       *
       * <code>int64 Interval = 3;</code>
       */
      public Builder clearInterval() {
        
        interval_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zhouyp.demo.proto.RtaStat.DB)
    }

    // @@protoc_insertion_point(class_scope:com.zhouyp.demo.proto.RtaStat.DB)
    private static final com.zhouyp.demo.proto.RtaStat.Stat.DB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhouyp.demo.proto.RtaStat.Stat.DB();
    }

    public static com.zhouyp.demo.proto.RtaStat.Stat.DB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DB>
        PARSER = new com.google.protobuf.AbstractParser<DB>() {
      @java.lang.Override
      public DB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DB> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zhouyp.demo.proto.RtaStat.Stat.DB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zhouyp.demo.proto.RtaStat.Table)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */
    int getFieldsCount();
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */
    boolean containsFields(
        java.lang.String key);
    /**
     * Use {@link #getFieldsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
    getFields();
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */
    java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
    getFieldsMap();
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */

    com.zhouyp.demo.proto.RtaStat.Stat.Values getFieldsOrDefault(
        java.lang.String key,
        com.zhouyp.demo.proto.RtaStat.Stat.Values defaultValue);
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */

    com.zhouyp.demo.proto.RtaStat.Stat.Values getFieldsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.zhouyp.demo.proto.RtaStat.Table}
   */
  public  static final class Table extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zhouyp.demo.proto.RtaStat.Table)
      TableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Table.newBuilder() to construct.
    private Table(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Table() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Table(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                fields_ = com.google.protobuf.MapField.newMapField(
                    FieldsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
              fields__ = input.readMessage(
                  FieldsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              fields_.getMutableMap().put(
                  fields__.getKey(), fields__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Table_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Table_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhouyp.demo.proto.RtaStat.Stat.Table.class, com.zhouyp.demo.proto.RtaStat.Stat.Table.Builder.class);
    }

    public static final int FIELDS_FIELD_NUMBER = 1;
    private static final class FieldsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>newDefaultInstance(
                  com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Table_FieldsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.zhouyp.demo.proto.RtaStat.Stat.Values.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> fields_;
    private com.google.protobuf.MapField<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
    internalGetFields() {
      if (fields_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FieldsDefaultEntryHolder.defaultEntry);
      }
      return fields_;
    }

    public int getFieldsCount() {
      return internalGetFields().getMap().size();
    }
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */

    public boolean containsFields(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFields().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFieldsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> getFields() {
      return getFieldsMap();
    }
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */

    public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> getFieldsMap() {
      return internalGetFields().getMap();
    }
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */

    public com.zhouyp.demo.proto.RtaStat.Stat.Values getFieldsOrDefault(
        java.lang.String key,
        com.zhouyp.demo.proto.RtaStat.Stat.Values defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> map =
          internalGetFields().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *Key为Field名称，Value为Field的值集合
     * </pre>
     *
     * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
     */

    public com.zhouyp.demo.proto.RtaStat.Stat.Values getFieldsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> map =
          internalGetFields().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetFields(),
          FieldsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> entry
           : internalGetFields().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
        fields__ = FieldsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, fields__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhouyp.demo.proto.RtaStat.Stat.Table)) {
        return super.equals(obj);
      }
      com.zhouyp.demo.proto.RtaStat.Stat.Table other = (com.zhouyp.demo.proto.RtaStat.Stat.Table) obj;

      if (!internalGetFields().equals(
          other.internalGetFields())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetFields().getMap().isEmpty()) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFields().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Table parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhouyp.demo.proto.RtaStat.Stat.Table prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhouyp.demo.proto.RtaStat.Table}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zhouyp.demo.proto.RtaStat.Table)
        com.zhouyp.demo.proto.RtaStat.Stat.TableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Table_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetFields();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableFields();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Table_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhouyp.demo.proto.RtaStat.Stat.Table.class, com.zhouyp.demo.proto.RtaStat.Stat.Table.Builder.class);
      }

      // Construct using com.zhouyp.demo.proto.RtaStat.Stat.Table.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableFields().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Table_descriptor;
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.Table getDefaultInstanceForType() {
        return com.zhouyp.demo.proto.RtaStat.Stat.Table.getDefaultInstance();
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.Table build() {
        com.zhouyp.demo.proto.RtaStat.Stat.Table result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.Table buildPartial() {
        com.zhouyp.demo.proto.RtaStat.Stat.Table result = new com.zhouyp.demo.proto.RtaStat.Stat.Table(this);
        int from_bitField0_ = bitField0_;
        result.fields_ = internalGetFields();
        result.fields_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhouyp.demo.proto.RtaStat.Stat.Table) {
          return mergeFrom((com.zhouyp.demo.proto.RtaStat.Stat.Table)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhouyp.demo.proto.RtaStat.Stat.Table other) {
        if (other == com.zhouyp.demo.proto.RtaStat.Stat.Table.getDefaultInstance()) return this;
        internalGetMutableFields().mergeFrom(
            other.internalGetFields());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhouyp.demo.proto.RtaStat.Stat.Table parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhouyp.demo.proto.RtaStat.Stat.Table) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> fields_;
      private com.google.protobuf.MapField<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
      internalGetFields() {
        if (fields_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FieldsDefaultEntryHolder.defaultEntry);
        }
        return fields_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
      internalGetMutableFields() {
        onChanged();;
        if (fields_ == null) {
          fields_ = com.google.protobuf.MapField.newMapField(
              FieldsDefaultEntryHolder.defaultEntry);
        }
        if (!fields_.isMutable()) {
          fields_ = fields_.copy();
        }
        return fields_;
      }

      public int getFieldsCount() {
        return internalGetFields().getMap().size();
      }
      /**
       * <pre>
       *Key为Field名称，Value为Field的值集合
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
       */

      public boolean containsFields(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetFields().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFieldsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> getFields() {
        return getFieldsMap();
      }
      /**
       * <pre>
       *Key为Field名称，Value为Field的值集合
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
       */

      public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> getFieldsMap() {
        return internalGetFields().getMap();
      }
      /**
       * <pre>
       *Key为Field名称，Value为Field的值集合
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
       */

      public com.zhouyp.demo.proto.RtaStat.Stat.Values getFieldsOrDefault(
          java.lang.String key,
          com.zhouyp.demo.proto.RtaStat.Stat.Values defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> map =
            internalGetFields().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *Key为Field名称，Value为Field的值集合
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
       */

      public com.zhouyp.demo.proto.RtaStat.Stat.Values getFieldsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> map =
            internalGetFields().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearFields() {
        internalGetMutableFields().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *Key为Field名称，Value为Field的值集合
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
       */

      public Builder removeFields(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFields().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values>
      getMutableFields() {
        return internalGetMutableFields().getMutableMap();
      }
      /**
       * <pre>
       *Key为Field名称，Value为Field的值集合
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
       */
      public Builder putFields(
          java.lang.String key,
          com.zhouyp.demo.proto.RtaStat.Stat.Values value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFields().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *Key为Field名称，Value为Field的值集合
       * </pre>
       *
       * <code>map&lt;string, .com.zhouyp.demo.proto.RtaStat.Values&gt; Fields = 1;</code>
       */

      public Builder putAllFields(
          java.util.Map<java.lang.String, com.zhouyp.demo.proto.RtaStat.Stat.Values> values) {
        internalGetMutableFields().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zhouyp.demo.proto.RtaStat.Table)
    }

    // @@protoc_insertion_point(class_scope:com.zhouyp.demo.proto.RtaStat.Table)
    private static final com.zhouyp.demo.proto.RtaStat.Stat.Table DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhouyp.demo.proto.RtaStat.Stat.Table();
    }

    public static com.zhouyp.demo.proto.RtaStat.Stat.Table getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Table>
        PARSER = new com.google.protobuf.AbstractParser<Table>() {
      @java.lang.Override
      public Table parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Table(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Table> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Table> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zhouyp.demo.proto.RtaStat.Stat.Table getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zhouyp.demo.proto.RtaStat.Values)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
     * </pre>
     *
     * <code>repeated int64 Value = 1;</code>
     */
    java.util.List<java.lang.Long> getValueList();
    /**
     * <pre>
     *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
     * </pre>
     *
     * <code>repeated int64 Value = 1;</code>
     */
    int getValueCount();
    /**
     * <pre>
     *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
     * </pre>
     *
     * <code>repeated int64 Value = 1;</code>
     */
    long getValue(int index);
  }
  /**
   * Protobuf type {@code com.zhouyp.demo.proto.RtaStat.Values}
   */
  public  static final class Values extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zhouyp.demo.proto.RtaStat.Values)
      ValuesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Values.newBuilder() to construct.
    private Values(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Values() {
      value_ = emptyLongList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Values(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                value_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              value_.addLong(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                value_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                value_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          value_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Values_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Values_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhouyp.demo.proto.RtaStat.Stat.Values.class, com.zhouyp.demo.proto.RtaStat.Stat.Values.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.LongList value_;
    /**
     * <pre>
     *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
     * </pre>
     *
     * <code>repeated int64 Value = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getValueList() {
      return value_;
    }
    /**
     * <pre>
     *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
     * </pre>
     *
     * <code>repeated int64 Value = 1;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <pre>
     *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
     * </pre>
     *
     * <code>repeated int64 Value = 1;</code>
     */
    public long getValue(int index) {
      return value_.getLong(index);
    }
    private int valueMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValueList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(valueMemoizedSerializedSize);
      }
      for (int i = 0; i < value_.size(); i++) {
        output.writeInt64NoTag(value_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(value_.getLong(i));
        }
        size += dataSize;
        if (!getValueList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valueMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhouyp.demo.proto.RtaStat.Stat.Values)) {
        return super.equals(obj);
      }
      com.zhouyp.demo.proto.RtaStat.Stat.Values other = (com.zhouyp.demo.proto.RtaStat.Stat.Values) obj;

      if (!getValueList()
          .equals(other.getValueList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhouyp.demo.proto.RtaStat.Stat.Values parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhouyp.demo.proto.RtaStat.Stat.Values prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhouyp.demo.proto.RtaStat.Values}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zhouyp.demo.proto.RtaStat.Values)
        com.zhouyp.demo.proto.RtaStat.Stat.ValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Values_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Values_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhouyp.demo.proto.RtaStat.Stat.Values.class, com.zhouyp.demo.proto.RtaStat.Stat.Values.Builder.class);
      }

      // Construct using com.zhouyp.demo.proto.RtaStat.Stat.Values.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhouyp.demo.proto.RtaStat.Stat.internal_static_com_zhouyp_demo_proto_RtaStat_Values_descriptor;
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.Values getDefaultInstanceForType() {
        return com.zhouyp.demo.proto.RtaStat.Stat.Values.getDefaultInstance();
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.Values build() {
        com.zhouyp.demo.proto.RtaStat.Stat.Values result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zhouyp.demo.proto.RtaStat.Stat.Values buildPartial() {
        com.zhouyp.demo.proto.RtaStat.Stat.Values result = new com.zhouyp.demo.proto.RtaStat.Stat.Values(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          value_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhouyp.demo.proto.RtaStat.Stat.Values) {
          return mergeFrom((com.zhouyp.demo.proto.RtaStat.Stat.Values)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhouyp.demo.proto.RtaStat.Stat.Values other) {
        if (other == com.zhouyp.demo.proto.RtaStat.Stat.Values.getDefaultInstance()) return this;
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhouyp.demo.proto.RtaStat.Stat.Values parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhouyp.demo.proto.RtaStat.Stat.Values) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList value_ = emptyLongList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          value_ = mutableCopy(value_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
       * </pre>
       *
       * <code>repeated int64 Value = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getValueList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(value_) : value_;
      }
      /**
       * <pre>
       *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
       * </pre>
       *
       * <code>repeated int64 Value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <pre>
       *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
       * </pre>
       *
       * <code>repeated int64 Value = 1;</code>
       */
      public long getValue(int index) {
        return value_.getLong(index);
      }
      /**
       * <pre>
       *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
       * </pre>
       *
       * <code>repeated int64 Value = 1;</code>
       */
      public Builder setValue(
          int index, long value) {
        ensureValueIsMutable();
        value_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
       * </pre>
       *
       * <code>repeated int64 Value = 1;</code>
       */
      public Builder addValue(long value) {
        ensureValueIsMutable();
        value_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
       * </pre>
       *
       * <code>repeated int64 Value = 1;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *测量点的数值，每Interval一个值。如实际该时间点无值，仍然会填入0
       * </pre>
       *
       * <code>repeated int64 Value = 1;</code>
       */
      public Builder clearValue() {
        value_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zhouyp.demo.proto.RtaStat.Values)
    }

    // @@protoc_insertion_point(class_scope:com.zhouyp.demo.proto.RtaStat.Values)
    private static final com.zhouyp.demo.proto.RtaStat.Stat.Values DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhouyp.demo.proto.RtaStat.Stat.Values();
    }

    public static com.zhouyp.demo.proto.RtaStat.Stat.Values getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Values>
        PARSER = new com.google.protobuf.AbstractParser<Values>() {
      @java.lang.Override
      public Values parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Values(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Values> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Values> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zhouyp.demo.proto.RtaStat.Stat.Values getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhouyp_demo_proto_RtaStat_DB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhouyp_demo_proto_RtaStat_DB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhouyp_demo_proto_RtaStat_DB_TablesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhouyp_demo_proto_RtaStat_DB_TablesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhouyp_demo_proto_RtaStat_Table_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhouyp_demo_proto_RtaStat_Table_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhouyp_demo_proto_RtaStat_Table_FieldsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhouyp_demo_proto_RtaStat_Table_FieldsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhouyp_demo_proto_RtaStat_Values_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhouyp_demo_proto_RtaStat_Values_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nstat.proto\022\035com.zhouyp.demo.proto.RtaS" +
      "tat\"\275\001\n\002DB\022=\n\006Tables\030\001 \003(\0132-.com.zhouyp." +
      "demo.proto.RtaStat.DB.TablesEntry\022\021\n\tTim" +
      "estamp\030\002 \001(\003\022\020\n\010Interval\030\003 \001(\003\032S\n\013Tables" +
      "Entry\022\013\n\003key\030\001 \001(\t\0223\n\005value\030\002 \001(\0132$.com." +
      "zhouyp.demo.proto.RtaStat.Table:\0028\001\"\237\001\n\005" +
      "Table\022@\n\006Fields\030\001 \003(\01320.com.zhouyp.demo." +
      "proto.RtaStat.Table.FieldsEntry\032T\n\013Field" +
      "sEntry\022\013\n\003key\030\001 \001(\t\0224\n\005value\030\002 \001(\0132%.com" +
      ".zhouyp.demo.proto.RtaStat.Values:\0028\001\"\027\n" +
      "\006Values\022\r\n\005Value\030\001 \003(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zhouyp_demo_proto_RtaStat_DB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zhouyp_demo_proto_RtaStat_DB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhouyp_demo_proto_RtaStat_DB_descriptor,
        new java.lang.String[] { "Tables", "Timestamp", "Interval", });
    internal_static_com_zhouyp_demo_proto_RtaStat_DB_TablesEntry_descriptor =
      internal_static_com_zhouyp_demo_proto_RtaStat_DB_descriptor.getNestedTypes().get(0);
    internal_static_com_zhouyp_demo_proto_RtaStat_DB_TablesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhouyp_demo_proto_RtaStat_DB_TablesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_zhouyp_demo_proto_RtaStat_Table_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zhouyp_demo_proto_RtaStat_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhouyp_demo_proto_RtaStat_Table_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_com_zhouyp_demo_proto_RtaStat_Table_FieldsEntry_descriptor =
      internal_static_com_zhouyp_demo_proto_RtaStat_Table_descriptor.getNestedTypes().get(0);
    internal_static_com_zhouyp_demo_proto_RtaStat_Table_FieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhouyp_demo_proto_RtaStat_Table_FieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_zhouyp_demo_proto_RtaStat_Values_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_zhouyp_demo_proto_RtaStat_Values_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhouyp_demo_proto_RtaStat_Values_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
